### ISSUE TITLE
can't see in plugin's

### ISSUE THREAD

**Issue by kylebassett** [chkal/rocket-chat-notifier#1]
Hi, I found your plugin - I was able to build the .hpi file and load into plugin's in Jenkins.  I never see the config options in the jenkins UI. it does show the plugin installed.  Am I missing something?

Thanks
Kyle

**Comment by kylebassett** [comment]
Human, error - the other plugin's seems to get enabled but this one I had to manually enable.  Thanks for the plugin... Kyle

**Comment by chkal** [comment]
Great to hear that you fixed your problem. :+1:
